version: '3'

services:
  faker:
    container_name: codeforces
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: codeforces
      SLEEP_TIME: 5

networks:
  default:
    external:
      name: kafka-network
